# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
mat=np.random.random((3,3,3))
mat

array([[[0.06470406, 0.39537823, 0.33721301],
        [0.72085536, 0.16086466, 0.05661252],
        [0.36865892, 0.79346339, 0.85383589]],

       [[0.36646001, 0.63727352, 0.41983215],
        [0.04885858, 0.31803781, 0.14998698],
        [0.1427856 , 0.64112806, 0.5469976 ]],

       [[0.28179864, 0.75868097, 0.8178914 ],
        [0.28564416, 0.76881834, 0.66217598],
        [0.69914864, 0.42485466, 0.9331431 ]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [62]:
import numpy as np
x=np.zeros((5,5),dtype=int)
for i in range(5):
    x[i]



array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [27]:
import numpy as np
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
x.mean(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

# 4. Normalize a 5x5 random matrix

In [29]:
import numpy as np
x= np.random.random((3,3))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.64864283 0.39795382 0.73705323]
 [0.77961642 0.98559639 0.83852478]
 [0.33597155 0.12871813 0.87106502]]
After normalization:
[[0.60676613 0.3142053  0.70994344]
 [0.75961583 1.         0.82836348]
 [0.24187032 0.         0.86633882]]


# 5.  How to find common values between two arrays?

In [64]:
a=np.arange(1,20)
b=np.arange(5,10)
print(np.intersect1d(a,b))

[5 6 7 8 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [75]:

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [71]:
a1=np.random.randint(1,10,30)
b1=np.random.randint(1,10,30)
print(a1==b1)
z=np.allclose(a1,b1)
z

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]


False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [31]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.97407026 0.02863155 0.43737273 0.48401995 0.41932242 0.3804071
 0.15617698 0.35277593 0.37317305 0.287704  ]
Maximum value replaced by 0:
[0.         0.02863155 0.43737273 0.48401995 0.41932242 0.3804071
 0.15617698 0.35277593 0.37317305 0.287704  ]


# 9. How to print all the values of an array?

In [37]:
arry=np.arange(10)
arry
print(*arry)

0 1 2 3 4 5 6 7 8 9


# 10.Subtract the mean of each row of a matrix

In [76]:
import numpy as np
orgi= np.random.rand(5, 10)
print(orgi)
subb = orgi - orgi.mean(axis=1, keepdims=True)
print(subb)



[[0.62803292 0.2599     0.82372391 0.08960178 0.06546082 0.82916504
  0.11031018 0.20932873 0.61480552 0.91865889]
 [0.05692799 0.1685761  0.44332485 0.90098444 0.86321754 0.02421171
  0.64288211 0.45100371 0.31618597 0.02251192]
 [0.85217049 0.45081375 0.53467233 0.24085239 0.76319488 0.73926247
  0.22842098 0.6104865  0.61422791 0.0632555 ]
 [0.15640888 0.29257943 0.00983462 0.24283353 0.03254495 0.07587181
  0.07307209 0.84587342 0.77281841 0.77629724]
 [0.93718888 0.62693139 0.18835271 0.45229478 0.06032793 0.27459973
  0.03574595 0.91101524 0.78580208 0.33243726]]
[[ 0.17313414 -0.19499877  0.36882513 -0.365297   -0.38943796  0.37426626
  -0.3445886  -0.24557005  0.15990674  0.46376011]
 [-0.33205464 -0.22040653  0.05434222  0.5120018   0.47423491 -0.36477092
   0.25389948  0.06202107 -0.07279666 -0.36647072]
 [ 0.34243477 -0.05892197  0.02493661 -0.26888333  0.25345917  0.22952675
  -0.28131474  0.10075078  0.10449219 -0.44648022]
 [-0.17140456 -0.03523401 -0.31797882 -0.08497991

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [35]:
a=np.array(np.arange(10))
b=np.arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 12.How to get the diagonal of a dot product?

In [29]:
x=np.arange(9).reshape(3,3)
y=np.arange(9).reshape(3,3)
z=x.dot(y)
print(z)
summ=0
for i in range(3):
    for j in range(3):
        if i==j:
            summ=summ+z[i][j]
print(summ)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
180


# 13.How to find the most frequent value in an array?

In [34]:
y=np.random.randint(0,10,30)
np.bincount(y).argmax()

8

# 14.How to get the n largest values of an array

In [32]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [33]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')

print(result)

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]
